In [88]:
import pandas as pd
import matplotlib.pyplot as plt
from joblib import dump, load

data = '211102_Data'
dataname = data+'_230320_08'
filename = 'myData/'+data+'.csv'
SD = pd.read_csv(filename)
SD=SD.iloc[:,:28]
SensorData = SD
SDext =SD # SensorData[SensorData['z']==0]
mask = SDext["z"].isin(list(range(37,127,3)))
SD = SDext[mask]
SD

,Sx00,Sx01,Sx02,Sx03,Sx04,Sx05,Sx06,Sx07,Sx08,Sx09,...,Sx12,Sx13,Sx14,Sx15,Sx16,Sx17,r,theta,theta_enc,z
103683,67.75,54.29,52.17,60.41,62.85,56.95,38.75,55.46,57.02,57.05,...,63.57,47.6,78.78,49.90,47.34,70.31,0.9,0,130.30,37
103684,70.07,52.77,51.28,61.30,61.91,57.82,32.10,53.66,60.66,57.05,...,63.57,47.6,77.92,52.63,49.38,70.31,0.9,0,130.30,37
103685,71.23,52.01,52.17,59.52,59.09,58.69,37.80,53.66,59.75,57.05,...,63.57,47.6,81.36,51.72,50.40,70.31,0.9,0,130.30,37
103686,67.75,51.25,51.28,62.19,60.03,56.08,35.90,55.46,57.93,57.05,...,63.57,47.6,77.06,48.99,49.38,69.42,0.9,0,130.30,37
103687,68.91,53.53,53.06,63.97,61.91,55.21,37.80,51.86,57.02,57.96,...,65.39,48.6,78.78,48.08,49.38,68.53,0.9,0,130.30,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449280,70.07,53.53,50.39,58.63,47.81,56.95,41.60,57.26,59.75,57.96,...,60.84,47.6,75.34,59.91,52.44,70.31,1.8,355,188.44,124
449281,70.07,55.81,51.28,58.63,48.75,57.82,36.85,58.16,59.75,54.32,...,62.66,47.6,78.78,55.36,53.46,70.31,1.8,355,188.44,124
449282,70.07,55.05,50.39,58.63,50.63,57.82,40.65,57.26,58.84,57.05,...,62.66,48.6,77.06,56.27,52.44,70.31,1.8,355,188.44,124
449283,70.07,54.29,51.28,59.52,50.63,58.69,40.65,56.36,59.75,57.96,...,61.75,46.6,78.78,55.36,51.42,67.64,1.8,355,188.44,124
449284,68.91,53.53,51.28,59.52,47.81,56.95,41.60,58.16,59.75,57.05,...,60.84,45.6,77.06,58.09,51.42,70.31,1.8,355,188.44,124

In [89]:
import numpy as np
toRad = np.pi/180.0
SD.loc[:, 'cos'] = np.cos(SD.loc[:, 'theta_enc']*toRad*2)
SD.loc[:, 'sin'] = np.sin(SD.loc[:, 'theta_enc']*toRad*2)
SD.loc[:, 'r'] = (SD.loc[:, 'r']-SD.loc[:, 'r'].mean())/(SD.loc[:, 'r'].max()-SD.loc[:, 'r'].min())*2
SD.loc[:, 'theta_enc'] = SD.loc[:, 'theta_enc'] - 180
SD.loc[:, 'theta_enc'] = (SD.loc[:, 'theta_enc']-SD.loc[:, 'theta_enc'].mean())/(SD.loc[:, 'theta_enc'].max()-SD.loc[:, 'theta_enc'].min())*2
SD.loc[:, 'z'] = (SD.loc[:, 'z']-SD.loc[:, 'z'].mean())/(SD.loc[:, 'z'].max()-SD.loc[:, 'z'].min())*2

C:\Users\JH_LAB\anaconda3\lib\site-packages\pandas\core\indexing.py:1667: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = value
C:\Users\JH_LAB\anaconda3\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

In [90]:
SDz=(SD.loc[:,'theta_enc'])
SDy = SD.iloc[:,24:30]
SDy

               r  theta  theta_enc    z       cos       sin
103683 -0.999996      0  -0.269045 -1.0 -0.163326 -0.986572
103684 -0.999996      0  -0.269045 -1.0 -0.163326 -0.986572
103685 -0.999996      0  -0.269045 -1.0 -0.163326 -0.986572
103686 -0.999996      0  -0.269045 -1.0 -0.163326 -0.986572
103687 -0.999996      0  -0.269045 -1.0 -0.163326 -0.986572
...          ...    ...        ...  ...       ...       ...
449280  1.000004    355   0.054108  1.0  0.956915  0.290368
449281  1.000004    355   0.054108  1.0  0.956915  0.290368
449282  1.000004    355   0.054108  1.0  0.956915  0.290368
449283  1.000004    355   0.054108  1.0  0.956915  0.290368
449284  1.000004    355   0.054108  1.0  0.956915  0.290368

[345602 rows x 6 columns]

In [91]:
X = SD.iloc[:,:24]
y = SD.iloc[:,[26]]
y

        theta_enc
103683  -0.269045
103684  -0.269045
103685  -0.269045
103686  -0.269045
103687  -0.269045
...           ...
449280   0.054108
449281   0.054108
449282   0.054108
449283   0.054108
449284   0.054108

[345602 rows x 1 columns]

In [97]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd

In [98]:
class SDDataset(Dataset):
    def __init__(self, data):
        self.data = data
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        x = torch.tensor(self.data.iloc[idx, :24].values, dtype=torch.float32)
        y = torch.tensor(self.data.iloc[idx, 26], dtype=torch.float32)
        return x, y

In [99]:
class SDModel(nn.Module):
    def __init__(self):
        super(SDModel, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(24, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )
        
    def forward(self, x):
        return self.layers(x)

In [100]:
# Assuming 'SD' is your DataFrame
data = SDDataset(SD)
batch_size = 64
data_loader = DataLoader(data, batch_size=batch_size, shuffle=True)

In [101]:
model = SDModel()
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

In [102]:
num_epochs = 100

for epoch in range(num_epochs):
    for inputs, targets in data_loader:
        # Forward pass
        outputs = model(inputs)
        loss = criterion(outputs.squeeze(), targets)
        
        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")

Epoch [1/100], Loss: 0.0958
Epoch [2/100], Loss: 0.0141
Epoch [3/100], Loss: 0.2200
Epoch [4/100], Loss: 0.0261
Epoch [5/100], Loss: 0.0463
Epoch [6/100], Loss: 0.0007
Epoch [7/100], Loss: 0.3825
Epoch [8/100], Loss: 0.0622
Epoch [9/100], Loss: 0.0380
Epoch [10/100], Loss: 0.0091
Epoch [11/100], Loss: 0.0910
Epoch [12/100], Loss: 0.0001
Epoch [13/100], Loss: 0.0064
Epoch [14/100], Loss: 0.0184
Epoch [15/100], Loss: 0.0667
Epoch [16/100], Loss: 0.4871
Epoch [17/100], Loss: 0.0342
Epoch [18/100], Loss: 0.0434
Epoch [19/100], Loss: 0.0015
Epoch [20/100], Loss: 0.0350
Epoch [21/100], Loss: 0.0172
Epoch [22/100], Loss: 0.1718
Epoch [23/100], Loss: 0.0479
Epoch [24/100], Loss: 0.0183
Epoch [25/100], Loss: 0.0250
Epoch [26/100], Loss: 0.0036
Epoch [27/100], Loss: 0.0164
Epoch [28/100], Loss: 0.0119
Epoch [29/100], Loss: 0.0279
Epoch [30/100], Loss: 0.1594
Epoch [31/100], Loss: 0.0563
Epoch [32/100], Loss: 0.0057
Epoch [33/100], Loss: 0.1362
Epoch [34/100], Loss: 1.2913
Epoch [35/100], Loss: 0.3035
Epoch [36/100], Loss: 0.0093
Epoch [37/100], Loss: 0.0581
Epoch [38/100], Loss: 0.0661
Epoch [39/100], Loss: 0.0298
Epoch [40/100], Loss: 0.0950
Epoch [41/100], Loss: 0.0194
Epoch [42/100], Loss: 0.0360
Epoch [43/100], Loss: 0.0136
Epoch [44/100], Loss: 0.0133
Epoch [45/100], Loss: 0.0033
Epoch [46/100], Loss: 0.0296
Epoch [47/100], Loss: 0.0077
Epoch [48/100], Loss: 0.6230
Epoch [49/100], Loss: 0.0015
Epoch [50/100], Loss: 0.0194
Epoch [51/100], Loss: 0.0253
Epoch [52/100], Loss: 0.1305
Epoch [53/100], Loss: 0.0047
Epoch [54/100], Loss: 0.0136
Epoch [55/100], Loss: 0.0191
Epoch [56/100], Loss: 0.0135
Epoch [57/100], Loss: 0.0093
Epoch [58/100], Loss: 0.0007
Epoch [59/100], Loss: 0.0253
Epoch [60/100], Loss: 0.0748
Epoch [61/100], Loss: 0.0011
Epoch [62/100], Loss: 0.0064
Epoch [63/100], Loss: 0.3219
Epoch [64/100], Loss: 0.0016
Epoch [65/100], Loss: 0.0032
Epoch [66/100], Loss: 0.0117
Epoch [67/100], Loss: 1.3757
Epoch [68/100], Loss: 0.0236
Epoch [69/100], Loss: 0.4796
Epoch [70/100], Loss: 0.0792
Epoch [71/100], Loss: 0.1086
Epoch [72/100], Loss: 0.0088
Epoch [73/100], Loss: 0.0061
Epoch [74/100], Loss: 0.0171
Epoch [75/100], Loss: 0.0090
Epoch [76/100], Loss: 0.0027
Epoch [77/100], Loss: 0.0092
Epoch [78/100], Loss: 0.0048
Epoch [79/100], Loss: 0.0026
Epoch [80/100], Loss: 0.0040
Epoch [81/100], Loss: 0.5040
Epoch [82/100], Loss: 0.0156
Epoch [83/100], Loss: 0.0064
Epoch [84/100], Loss: 0.0458
Epoch [85/100], Loss: 0.0575
Epoch [86/100], Loss: 0.0282
Epoch [87/100], Loss: 0.0060
Epoch [88/100], Loss: 0.0030
Epoch [89/100], Loss: 0.0163
Epoch [90/100], Loss: 0.0144
Epoch [91/100], Loss: 0.1590
Epoch [92/100], Loss: 0.0421
Epoch [93/100], Loss: 0.0241
Epoch [94/100], Loss: 0.3864
Epoch [95/100], Loss: 0.0365
Epoch [96/100], Loss: 0.1061
Epoch [97/100], Loss: 0.2348
Epoch [98/100], Loss: 0.0000
Epoch [99/100], Loss: 0.0814
Epoch [100/100], Loss: 0.0112